"""Initial migration

Revision ID: 0c96d9b03b48
Revises: 
Create Date: 2025-09-30 17:18:12.857302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c96d9b03b48'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_name', sa.String(length=255), nullable=False),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_id'), 'suppliers', ['id'], unique=False)
    op.create_table('vehicle_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_number', sa.String(length=50), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('bill_no', sa.String(length=100), nullable=False),
    sa.Column('driver_name', sa.String(length=255), nullable=True),
    sa.Column('driver_phone', sa.String(length=20), nullable=True),
    sa.Column('arrival_time', sa.DateTime(), nullable=True),
    sa.Column('supplier_bill_photo', sa.LargeBinary(), nullable=True),
    sa.Column('vehicle_photo', sa.LargeBinary(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_entries_id'), 'vehicle_entries', ['id'], unique=False)
    op.create_table('lab_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_entry_id', sa.Integer(), nullable=False),
    sa.Column('test_date', sa.DateTime(), nullable=True),
    sa.Column('moisture', sa.Float(), nullable=True),
    sa.Column('test_weight', sa.Float(), nullable=True),
    sa.Column('protein_percent', sa.Float(), nullable=True),
    sa.Column('wet_gluten', sa.Float(), nullable=True),
    sa.Column('dry_gluten', sa.Float(), nullable=True),
    sa.Column('falling_number', sa.Integer(), nullable=True),
    sa.Column('chaff_husk', sa.Float(), nullable=True),
    sa.Column('straws_sticks', sa.Float(), nullable=True),
    sa.Column('other_foreign_matter', sa.Float(), nullable=True),
    sa.Column('mudballs', sa.Float(), nullable=True),
    sa.Column('stones', sa.Float(), nullable=True),
    sa.Column('dust_sand', sa.Float(), nullable=True),
    sa.Column('total_impurities', sa.Float(), nullable=True),
    sa.Column('shriveled_wheat', sa.Float(), nullable=True),
    sa.Column('insect_damage', sa.Float(), nullable=True),
    sa.Column('blackened_wheat', sa.Float(), nullable=True),
    sa.Column('sprouted_grains', sa.Float(), nullable=True),
    sa.Column('other_grain_damage', sa.Float(), nullable=True),
    sa.Column('total_dockage', sa.Float(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('tested_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_entry_id'], ['vehicle_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_tests_id'), 'lab_tests', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lab_tests_id'), table_name='lab_tests')
    op.drop_table('lab_tests')
    op.drop_index(op.f('ix_vehicle_entries_id'), table_name='vehicle_entries')
    op.drop_table('vehicle_entries')
    op.drop_index(op.f('ix_suppliers_id'), table_name='suppliers')
    op.drop_table('suppliers')
    # ### end Alembic commands ###
